version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d:rw
      - ./html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy

  version: '3'

  services:
    postfix:
      image: postfix:latest
      volumes:
        - ./postfix_data:/var/spool/postfix
        - ./postfix_config:/etc/postfix
      environment:
        - MAILNAME=example.com
      ports:
        - "25:25"
        - "587:587"

    dovecot:
      image: dovecot:latest
      volumes:
        - ./dovecot_data:/var/mail
        - ./dovecot_config:/etc/dovecot
      ports:
        - "110:110"
        - "143:143"
        - "993:993"
        - "995:995"

  volumes:
    postfix_data:
    postfix_config:
    dovecot_data:
    dovecot_config:

  bind9:
    image: internetsystemsconsortium/bind9:9.16
    restart: always
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./bind:/etc/bind
      - ./bind/cache:/var/cache/bind
      - ./bind/records:/var/lib/bind

volumes:
  mysql-data:

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: myapp
      MYSQL_USER: myapp
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    image: ${DOCKER_IMAGE}
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=myapp
      - DB_USERNAME=myapp
      - DB_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
    command: ["php", "artisan", "migrate", "--seed"]